### PR TITLE
Added the new coral option to docs

### PR DESCRIPTION
**Pull request by Jazzkuh**
Added the new coral option from build 1696 to the docs

### CODE REVIEW

**Review by granny — CHANGES_REQUESTED** [review]
https://github.com/PurpurMC/PurpurDocs/blob/4e0e121ba60403031a5630bc5a22974567469d02/mkdocs.yml#L67-L69

build number and commit need to be updated here

**Comment by Jazzkuh** [comment]
Made the changes

**Comment by emielderckx** [comment]
There have been added more features between these builds:
[459e5f1] Option to disable kick for out of order chat
[49a4494] Config for sculk shrieker can_summon state

**Comment by Jazzkuh** [comment]
> There have been added more features between these builds: [459e5f1] Option to disable kick for out of order chat [49a4494] Config for sculk shrieker can_summon state

Added

**Review by granny — APPROVED** [review]

**Pull request merged**
